import "bootstrap/dist/css/bootstrap.min.css"
import BootstrapClient from "@/components/BootstrapClient";
import "./globals.css"

export const metadata = {
  title: "Home | Maple Bank",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>
        <BootstrapClient/>
        {children}
      </body>
    </html>
  );
}
